import { createHash } from "node:crypto";

export type CommentSyntax = "<!-- -->" | "#" | "//";

export interface HeaderFields {
  assetId: string;
  source: string;
  hash: string;
  commentSyntax: CommentSyntax;
}

const HEADER_MARKER = "DO NOT EDIT — generated by coactl";

export function contentHash(body: string): string {
  return "sha256-" + createHash("sha256").update(body).digest("hex");
}

export function renderHeader(fields: HeaderFields): string {
  const lines = [HEADER_MARKER, `asset: ${fields.assetId}`, `source: ${fields.source}`, `hash: ${fields.hash}`];

  if (fields.commentSyntax === "<!-- -->") {
    return `<!--\n${lines.map((l) => `  ${l}`).join("\n")}\n-->\n`;
  } else if (fields.commentSyntax === "#") {
    return lines.map((l) => `# ${l}`).join("\n") + "\n";
  } else {
    return lines.map((l) => `// ${l}`).join("\n") + "\n";
  }
}

export function parseHeader(fileContents: string): { assetId: string; source: string; hash: string } | null {
  let headerText: string | null = null;

  // Some native formats require YAML frontmatter before generated comments. Accept a
  // Coactl header after that frontmatter while still requiring the exact header marker.
  const htmlMatch = fileContents.match(/(?:^|\n)<!--\n([\s\S]*?)-->\n/);
  if (htmlMatch) {
    headerText = htmlMatch[1];
  } else {
    const lines = fileContents.split("\n");
    const commentLines: string[] = [];
    for (const line of lines) {
      if (line.startsWith("# ") || line.startsWith("// ")) {
        commentLines.push(line.slice(2));
      } else {
        break;
      }
    }
    if (commentLines.length > 0) {
      headerText = commentLines.join("\n");
    }
  }

  if (!headerText) return null;

  const assetMatch = headerText.match(/asset:\s*(.+)/);
  const sourceMatch = headerText.match(/source:\s*(.+)/);
  const hashMatch = headerText.match(/hash:\s*(.+)/);

  if (!assetMatch || !sourceMatch || !hashMatch) return null;

  return {
    assetId: assetMatch[1].trim(),
    source: sourceMatch[1].trim(),
    hash: hashMatch[1].trim(),
  };
}
