import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { listAssets, sourceHint } from "../../src/cli/commands/import.js";

let tmp: string | undefined;
const originalCwd = process.cwd();

afterEach(() => {
  process.chdir(originalCwd);
  if (tmp) rmSync(tmp, { recursive: true, force: true });
  tmp = undefined;
});

describe("import command sources", () => {
  it("lists Codex project skills and AGENTS.md rules", () => {
    tmp = mkdtempSync(join(tmpdir(), "coactl-import-"));
    process.chdir(tmp);

    mkdirSync(join(tmp, ".agents", "skills", "codex-skill"), { recursive: true });
    writeFileSync(
      join(tmp, ".agents", "skills", "codex-skill", "SKILL.md"),
      [
        "---",
        "name: codex-skill",
        "description: Import me",
        "---",
        "",
        "<!--",
        "DO NOT EDIT — generated by coactl",
        "-->",
        "# Codex Skill",
        "",
      ].join("\n"),
    );
    writeFileSync(
      join(tmp, "AGENTS.md"),
      [
        "<!-- BEGIN coactl:codex-rule -->",
        "<!--",
        "DO NOT EDIT — generated by coactl",
        "-->",
        "Use the repo conventions.",
        "<!-- END coactl:codex-rule -->",
        "",
      ].join("\n"),
    );

    const assets = listAssets("codex", false);

    expect(assets).toEqual([
      {
        id: "codex-skill",
        kind: "skill",
        body: "# Codex Skill\n",
        description: "Import me",
      },
      {
        id: "codex-rule",
        kind: "rule",
        body: "Use the repo conventions.",
      },
    ]);
    expect(sourceHint("codex", false)).toContain("AGENTS.md");
  });

  it("lists Antigravity project skills, commands, and AGENTS.md rules", () => {
    tmp = mkdtempSync(join(tmpdir(), "coactl-import-"));
    process.chdir(tmp);

    mkdirSync(join(tmp, ".antigravity", "skills", "ag-skill"), { recursive: true });
    writeFileSync(
      join(tmp, ".antigravity", "skills", "ag-skill", "SKILL.md"),
      [
        "---",
        "name: ag-skill",
        "description: Antigravity skill",
        "---",
        "",
        "<!--",
        "DO NOT EDIT — generated by coactl",
        "-->",
        "# Antigravity Skill",
        "",
      ].join("\n"),
    );
    mkdirSync(join(tmp, ".antigravity", "commands"), { recursive: true });
    writeFileSync(
      join(tmp, ".antigravity", "commands", "ag-command.md"),
      [
        "---",
        "description: Antigravity command",
        "---",
        "",
        "# Antigravity Command",
        "",
      ].join("\n"),
    );
    writeFileSync(
      join(tmp, "AGENTS.md"),
      [
        "<!-- BEGIN coactl:ag-rule -->",
        "<!--",
        "DO NOT EDIT — generated by coactl",
        "-->",
        "Use Antigravity conventions.",
        "<!-- END coactl:ag-rule -->",
        "",
      ].join("\n"),
    );

    const assets = listAssets("antigravity", false);

    expect(assets).toEqual([
      {
        id: "ag-skill",
        kind: "skill",
        body: "# Antigravity Skill\n",
        description: "Antigravity skill",
      },
      {
        id: "ag-command",
        kind: "command",
        body: "# Antigravity Command\n",
        description: "Antigravity command",
      },
      {
        id: "ag-rule",
        kind: "rule",
        body: "Use Antigravity conventions.",
      },
    ]);
    expect(sourceHint("antigravity", false)).toContain(".antigravity/skills");
  });

  it("lists Gemini project skills and GEMINI.md rules", () => {
    tmp = mkdtempSync(join(tmpdir(), "coactl-import-"));
    process.chdir(tmp);

    mkdirSync(join(tmp, ".gemini", "skills", "gemini-skill"), { recursive: true });
    writeFileSync(
      join(tmp, ".gemini", "skills", "gemini-skill", "SKILL.md"),
      ["---", "name: gemini-skill", "description: Gemini skill", "---", "", "# Gemini Skill", ""].join("\n"),
    );
    writeFileSync(
      join(tmp, "GEMINI.md"),
      [
        "<!-- BEGIN coactl:gemini-rule -->",
        "Use Gemini conventions.",
        "<!-- END coactl:gemini-rule -->",
        "",
      ].join("\n"),
    );

    const assets = listAssets("gemini", false);

    expect(assets).toEqual([
      {
        id: "gemini-skill",
        kind: "skill",
        body: "# Gemini Skill\n",
        description: "Gemini skill",
      },
      {
        id: "gemini-rule",
        kind: "rule",
        body: "Use Gemini conventions.",
      },
    ]);
    expect(sourceHint("gemini", false)).toContain("GEMINI.md");
  });
});
