import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { listAssets, sourceHint } from "../../src/cli/commands/import.js";

let tmp: string | undefined;
const originalCwd = process.cwd();

afterEach(() => {
  process.chdir(originalCwd);
  if (tmp) rmSync(tmp, { recursive: true, force: true });
  tmp = undefined;
});

describe("import command sources", () => {
  it("lists Codex project skills and AGENTS.md rules", () => {
    tmp = mkdtempSync(join(tmpdir(), "coactl-import-"));
    process.chdir(tmp);

    mkdirSync(join(tmp, ".agents", "skills", "codex-skill"), { recursive: true });
    writeFileSync(
      join(tmp, ".agents", "skills", "codex-skill", "SKILL.md"),
      [
        "---",
        "name: codex-skill",
        "description: Import me",
        "---",
        "",
        "<!--",
        "DO NOT EDIT — generated by coactl",
        "-->",
        "# Codex Skill",
        "",
      ].join("\n"),
    );
    writeFileSync(
      join(tmp, "AGENTS.md"),
      [
        "<!-- BEGIN coactl:codex-rule -->",
        "<!--",
        "DO NOT EDIT — generated by coactl",
        "-->",
        "Use the repo conventions.",
        "<!-- END coactl:codex-rule -->",
        "",
      ].join("\n"),
    );

    const assets = listAssets("codex", false);

    expect(assets).toEqual([
      {
        id: "codex-skill",
        kind: "skill",
        body: "# Codex Skill\n",
        description: "Import me",
      },
      {
        id: "codex-rule",
        kind: "rule",
        body: "Use the repo conventions.",
      },
    ]);
    expect(sourceHint("codex", false)).toContain("AGENTS.md");
  });
});
