import { describe, expect, it } from "vitest";
import { CodexAdapter } from "../../src/adapters/codex.js";
import type { ResolvedAsset } from "../../src/registry/types.js";

function asset(kind: "skill" | "command" | "rule" | "workflow"): ResolvedAsset {
  return {
    asset: {
      id: "review-code",
      kind,
      name: "Review Code",
      version: "1.0.0",
      description: "Review a code change.",
      activation: kind === "rule" ? "auto" : "manual",
      targets: ["claude-code", "codex"],
    },
    bodyText: "# Review\n\nInspect the change.\n",
    sourceName: "local",
    readOnly: false,
    origin: { dir: "/tmp/review-code" },
    provenance: { winningSource: "local", candidates: [{ sourceName: "local", readOnly: false }] },
  };
}

describe("CodexAdapter", () => {
  const adapter = new CodexAdapter();

  it("maps skills and rules to native Codex project locations", () => {
    const skill = adapter.emit(asset("skill"), { scope: "project" });
    const rule = adapter.emit(asset("rule"), { scope: "project" });

    expect(skill[0].path).toBe(".agents/skills/review-code/SKILL.md");
    expect(skill[0].contents).toContain("name: review-code");
    expect(skill[0].contents).toContain("DO NOT EDIT — generated by coactl");
    expect(rule[0].path).toBe("AGENTS.md");
    expect(rule[0].contents).toContain("<!-- BEGIN coactl:review-code -->");
    expect(rule[0].contents).toContain("<!-- END coactl:review-code -->");
  });

  it("maps global rules and commands to the configured Codex home", () => {
    const context = { scope: "global" as const, codexHome: "/tmp/codex-home" };
    const rule = adapter.emit(asset("rule"), context);
    const command = adapter.emit(asset("command"), context);

    expect(rule[0].path).toBe("/tmp/codex-home/AGENTS.md");
    expect(command[0].path).toBe("/tmp/codex-home/prompts/review-code.md");
    expect(command[0].contents).toContain("description: \"Review a code change.\"");
  });

  it("does not emit project commands or workflows", () => {
    expect(adapter.emit(asset("command"), { scope: "project" })).toEqual([]);
    expect(adapter.emit(asset("workflow"), { scope: "global", codexHome: "/tmp/codex-home" })).toEqual([]);
  });
});
