import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import type { EmittedFile } from "../adapters/types.js";
import type { Target } from "../schema/index.js";
import { codexConfigDir } from "./global-paths.js";

export interface WriteSummary {
  written: number;
  unchanged: number;
  errors: Array<{ path: string; error: string }>;
}

// Files that should be merged rather than replaced
export const MANAGED_AGGREGATE_FILES = new Set([
  "CLAUDE.md",
  ".windsurfrules",
  ".github/copilot-instructions.md",
]);

const HEADER_MARKER = "DO NOT EDIT — generated by coactl";

export interface PruneOptions {
  rootDir: string;
  scope: "project" | "global";
  targets: Target[];
  dryRun?: boolean;
}

export interface PruneSummary {
  pruned: string[];
  errors: Array<{ path: string; error: string }>;
}

function getManagedBlockMarkers(path: string, assetId: string): { start: string; end: string } {
  return {
    start: `<!-- BEGIN coactl:${assetId} -->`,
    end: `<!-- END coactl:${assetId} -->`,
  };
}

function isManagedFile(path: string): boolean {
  return MANAGED_AGGREGATE_FILES.has(path) || basename(path) === "AGENTS.md";
}

function mergeWithManagedBlock(
  existingContent: string | null,
  newContent: string,
  assetId: string,
): string {
  const markers = getManagedBlockMarkers(existingContent ? "." : "", assetId);

  if (!existingContent) {
    return newContent;
  }

  // Remove old block for this asset if it exists
  const startIdx = existingContent.indexOf(markers.start);
  if (startIdx !== -1) {
    const endIdx = existingContent.indexOf(markers.end);
    if (endIdx !== -1) {
      const before = existingContent.substring(0, startIdx);
      const after = existingContent.substring(endIdx + markers.end.length);
      return before + newContent + after;
    }
  }

  // No existing block, just append
  return existingContent + "\n" + newContent;
}

export function writeFiles(files: EmittedFile[], rootDir: string = process.cwd()): WriteSummary {
  const summary: WriteSummary = {
    written: 0,
    unchanged: 0,
    errors: [],
  };

  // Group files by path (multiple assets may emit the same file)
  const filesByPath = new Map<string, EmittedFile[]>();
  for (const file of files) {
    const key = file.path;
    if (!filesByPath.has(key)) {
      filesByPath.set(key, []);
    }
    filesByPath.get(key)!.push(file);
  }

  for (const [path, emittedFiles] of filesByPath.entries()) {
    try {
      const fullPath = resolve(rootDir, path);
      const dir = dirname(fullPath);

      // Create parent directories
      if (!existsSync(dir)) {
        mkdirSync(dir, { recursive: true });
      }

      let content: string;

      if (isManagedFile(path)) {
        // Merge managed blocks
        const existing = existsSync(fullPath) ? readFileSync(fullPath, "utf-8") : null;
        let merged = existing;
        for (const file of emittedFiles) {
          merged = mergeWithManagedBlock(merged, file.contents, file.assetId);
        }
        content = merged || "";
      } else {
        // Single file write (non-managed aggregate files)
        if (emittedFiles.length > 1) {
          throw new Error(`Multiple emitters for non-managed file (expected 1, got ${emittedFiles.length})`);
        }
        content = emittedFiles[0].contents;
      }

      // Check if content changed
      if (existsSync(fullPath)) {
        const existing = readFileSync(fullPath, "utf-8");
        if (existing === content) {
          summary.unchanged++;
          continue;
        }
      }

      // Write file
      writeFileSync(fullPath, content, "utf-8");
      summary.written++;
    } catch (err) {
      summary.errors.push({
        path,
        error: (err as Error).message,
      });
    }
  }

  return summary;
}

function managedAssetId(contents: string): string | undefined {
  if (!contents.includes(HEADER_MARKER)) return undefined;
  const asset = contents.match(/(?:^|\n)\s*asset:\s*([^\n\r]+)/);
  return asset?.[1]?.trim();
}

function collectFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...collectFiles(path));
    else if (entry.isFile()) files.push(path);
  }
  return files;
}

function targetLocations(options: PruneOptions, target: Target): { dirs: string[]; aggregateFiles: string[] } {
  const root = options.rootDir;
  switch (target) {
    case "claude-code":
      return { dirs: [join(root, ".claude", "skills"), join(root, ".claude", "commands"), join(root, ".claude", "rules")], aggregateFiles: [] };
    case "codex":
      return {
        dirs: [
          join(root, ".agents", "skills"),
          ...(options.scope === "global" ? [join(codexConfigDir(), "prompts")] : []),
        ],
        aggregateFiles: [options.scope === "global" ? join(codexConfigDir(), "AGENTS.md") : join(root, "AGENTS.md")],
      };
    case "cursor":
      return { dirs: [join(root, ".cursor", "rules")], aggregateFiles: [] };
    case "windsurf":
      return { dirs: [], aggregateFiles: [join(root, ".windsurfrules")] };
    case "copilot":
      return { dirs: [], aggregateFiles: [join(root, ".github", "copilot-instructions.md")] };
  }
}

function removeStaleBlocks(contents: string, expectedAssetIds: Set<string>): { contents: string; ids: string[] } {
  const ids: string[] = [];
  const next = contents.replace(
    /<!-- BEGIN coactl:([a-z0-9-]+) -->\n?[\s\S]*?<!-- END coactl:\1 -->\n?/g,
    (block, id: string) => {
      if (expectedAssetIds.has(id)) return block;
      ids.push(id);
      return "";
    },
  );
  return { contents: next, ids };
}

// Pruning is intentionally conservative: standalone files are deleted only when they
// contain Coactl's generated header, and aggregate files lose only fenced Coactl blocks.
export function pruneManagedOutputs(files: EmittedFile[], options: PruneOptions): PruneSummary {
  const summary: PruneSummary = { pruned: [], errors: [] };
  const expectedByPath = new Map<string, Set<string>>();
  for (const file of files) {
    const path = resolve(options.rootDir, file.path);
    const ids = expectedByPath.get(path) ?? new Set<string>();
    ids.add(file.assetId);
    expectedByPath.set(path, ids);
  }

  for (const target of options.targets) {
    const locations = targetLocations(options, target);
    for (const dir of locations.dirs) {
      for (const path of collectFiles(dir)) {
        try {
          const assetId = managedAssetId(readFileSync(path, "utf-8"));
          if (!assetId || expectedByPath.get(path)?.has(assetId)) continue;
          summary.pruned.push(path);
          if (!options.dryRun) rmSync(path);
        } catch (err) {
          summary.errors.push({ path, error: (err as Error).message });
        }
      }
    }

    for (const path of locations.aggregateFiles) {
      if (!existsSync(path)) continue;
      try {
        const existing = readFileSync(path, "utf-8");
        const { contents, ids } = removeStaleBlocks(existing, expectedByPath.get(path) ?? new Set());
        if (ids.length === 0) continue;
        summary.pruned.push(...ids.map((id) => `${path}#${id}`));
        if (!options.dryRun) writeFileSync(path, contents, "utf-8");
      } catch (err) {
        summary.errors.push({ path, error: (err as Error).message });
      }
    }
  }

  return summary;
}
